"""small_fix

Revision ID: 1433cbe5e50b
Revises: 1803fb58a406
Create Date: 2025-12-18 01:00:39.260701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1433cbe5e50b'
down_revision: Union[str, Sequence[str], None] = '1803fb58a406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_forms', 'question_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_forms', 'question_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
